### ISSUE TITLE
duplicated  project

### ISSUE THREAD

**Issue by judovana** [ststeiger/procyon#4]
hi!

Please remove the project or make official fork from https://github.com/mstrobel/procyon - procyon had moved to github. This project is misselading, and for some reason indexed by websearches very high

**Comment by ststeiger** [comment]
The original procyon was on bitbucket, and therefore hard-to-find.
This project is a fork of an older version of procyon from bitbucket. 
Probably my project has more backlinks and exists since a longer time, hence the higher ranking in google. 
I still need it, so I'm going to keep it. 
I have added the necessary information in the readme-file, though.

**Comment by judovana** [comment]
And don't you want to fork the offical procyon?  https://github.com/mstrobel/procyon ?  it had really moved from butbucket to github. You miss the commit history, and by forking from  https://github.com/mstrobel/procyon  you will recive current version. Please at least remove the misleading informations about bitbucket, and correct them to  https://github.com/mstrobel/procyon  TYVM!

**Comment by judovana** [comment]
Sorry, yo already updated reame and comp. TY!
